/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_SLASH_GT = 2,
  anon_sym_GT = 3,
  anon_sym_LT_SLASH = 4,
  anon_sym_EQ = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_LPAREN = 8,
  anon_sym_RPAREN = 9,
  anon_sym_BANG = 10,
  anon_sym_DASH = 11,
  anon_sym_STAR = 12,
  anon_sym_SLASH = 13,
  anon_sym_PERCENT = 14,
  anon_sym_PLUS = 15,
  anon_sym_LT_EQ = 16,
  anon_sym_GT_EQ = 17,
  anon_sym_EQ_EQ = 18,
  anon_sym_BANG_EQ = 19,
  anon_sym_AMP_AMP = 20,
  anon_sym_PIPE_PIPE = 21,
  anon_sym_QMARK = 22,
  anon_sym_COLON = 23,
  sym_number_literal = 24,
  anon_sym_true = 25,
  anon_sym_false = 26,
  sym_null_literal = 27,
  anon_sym_DOT = 28,
  anon_sym_DQUOTE = 29,
  sym_string_content = 30,
  sym_text = 31,
  sym_tag_name = 32,
  sym_identifier = 33,
  sym_source_file = 34,
  sym_element = 35,
  sym_self_closing_element = 36,
  sym_container_element = 37,
  sym_child = 38,
  sym_attribute = 39,
  sym_expression_block = 40,
  sym_expression = 41,
  sym_unary_expression = 42,
  sym_binary_expression = 43,
  sym_conditional_expression = 44,
  sym_literal = 45,
  sym_boolean_literal = 46,
  sym_reference = 47,
  sym_member_access = 48,
  sym_string = 49,
  aux_sym_self_closing_element_repeat1 = 50,
  aux_sym_container_element_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_PLUS] = "+",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_QMARK] = "\?",
  [anon_sym_COLON] = ":",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null_literal] = "null_literal",
  [anon_sym_DOT] = ".",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_text] = "text",
  [sym_tag_name] = "tag_name",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_element] = "element",
  [sym_self_closing_element] = "self_closing_element",
  [sym_container_element] = "container_element",
  [sym_child] = "child",
  [sym_attribute] = "attribute",
  [sym_expression_block] = "expression_block",
  [sym_expression] = "expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_conditional_expression] = "conditional_expression",
  [sym_literal] = "literal",
  [sym_boolean_literal] = "boolean_literal",
  [sym_reference] = "reference",
  [sym_member_access] = "member_access",
  [sym_string] = "string",
  [aux_sym_self_closing_element_repeat1] = "self_closing_element_repeat1",
  [aux_sym_container_element_repeat1] = "container_element_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null_literal] = sym_null_literal,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_text] = sym_text,
  [sym_tag_name] = sym_tag_name,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_element] = sym_element,
  [sym_self_closing_element] = sym_self_closing_element,
  [sym_container_element] = sym_container_element,
  [sym_child] = sym_child,
  [sym_attribute] = sym_attribute,
  [sym_expression_block] = sym_expression_block,
  [sym_expression] = sym_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_conditional_expression] = sym_conditional_expression,
  [sym_literal] = sym_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_reference] = sym_reference,
  [sym_member_access] = sym_member_access,
  [sym_string] = sym_string,
  [aux_sym_self_closing_element_repeat1] = aux_sym_self_closing_element_repeat1,
  [aux_sym_container_element_repeat1] = aux_sym_container_element_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_element] = {
    .visible = true,
    .named = true,
  },
  [sym_container_element] = {
    .visible = true,
    .named = true,
  },
  [sym_child] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_block] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_member_access] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_self_closing_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_container_element_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternate = 1,
  field_condition = 2,
  field_consequent = 3,
  field_expression = 4,
  field_left = 5,
  field_name = 6,
  field_object = 7,
  field_operand = 8,
  field_operator = 9,
  field_property = 10,
  field_right = 11,
  field_value = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternate] = "alternate",
  [field_condition] = "condition",
  [field_consequent] = "consequent",
  [field_expression] = "expression",
  [field_left] = "left",
  [field_name] = "name",
  [field_object] = "object",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_property] = "property",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 3},
  [7] = {.index = 10, .length = 2},
  [8] = {.index = 12, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 0},
    {field_value, 2},
  [3] =
    {field_operand, 1},
    {field_operator, 0},
  [5] =
    {field_expression, 1},
  [6] =
    {field_value, 1},
  [7] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [10] =
    {field_object, 0},
    {field_property, 2},
  [12] =
    {field_alternate, 4},
    {field_condition, 0},
    {field_consequent, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 3,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 32,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 21,
  [45] = 45,
  [46] = 46,
  [47] = 26,
  [48] = 45,
  [49] = 49,
  [50] = 50,
  [51] = 50,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 55,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '!', 28,
        '"', 49,
        '%', 33,
        '&', 3,
        '(', 25,
        ')', 26,
        '*', 30,
        '+', 34,
        '-', 29,
        '.', 48,
        '/', 32,
        ':', 42,
        '<', 15,
        '=', 22,
        '>', 19,
        '?', 41,
        'f', 55,
        'n', 64,
        't', 61,
        '{', 23,
        '|', 10,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 27,
        '"', 49,
        '(', 25,
        '-', 29,
        '<', 14,
        '=', 21,
        '>', 18,
        'f', 55,
        'n', 64,
        't', 61,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 7,
        '%', 33,
        '&', 3,
        ')', 26,
        '*', 30,
        '+', 34,
        '-', 29,
        '.', 48,
        '/', 31,
        ':', 42,
        '<', 16,
        '=', 8,
        '>', 19,
        '?', 41,
        '|', 10,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 3:
      if (lookahead == '&') ADVANCE(39);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(9);
      if (lookahead == '>') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 6:
      if (lookahead == '<') ADVANCE(4);
      if (lookahead == '{') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == '|') ADVANCE(40);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(36);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(37);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_null_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 5},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 6},
  [50] = {.lex_state = 50},
  [51] = {.lex_state = 50},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 5},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null_literal] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(62),
    [sym_element] = STATE(69),
    [sym_self_closing_element] = STATE(54),
    [sym_container_element] = STATE(54),
    [anon_sym_LT] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_null_literal,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(24), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_reference,
      sym_member_access,
    STATE(17), 2,
      sym_boolean_literal,
      sym_string,
    STATE(18), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_conditional_expression,
      sym_literal,
  [41] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_null_literal,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(32), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_reference,
      sym_member_access,
    STATE(17), 2,
      sym_boolean_literal,
      sym_string,
    STATE(18), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_conditional_expression,
      sym_literal,
  [82] = 3,
    ACTIONS(23), 1,
      anon_sym_DOT,
    ACTIONS(19), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 15,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [107] = 2,
    ACTIONS(25), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(27), 16,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_DOT,
  [130] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_null_literal,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(28), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_reference,
      sym_member_access,
    STATE(17), 2,
      sym_boolean_literal,
      sym_string,
    STATE(18), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_conditional_expression,
      sym_literal,
  [171] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_null_literal,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(31), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_reference,
      sym_member_access,
    STATE(17), 2,
      sym_boolean_literal,
      sym_string,
    STATE(18), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_conditional_expression,
      sym_literal,
  [212] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_null_literal,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(22), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_reference,
      sym_member_access,
    STATE(17), 2,
      sym_boolean_literal,
      sym_string,
    STATE(18), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_conditional_expression,
      sym_literal,
  [253] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_null_literal,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(20), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_reference,
      sym_member_access,
    STATE(17), 2,
      sym_boolean_literal,
      sym_string,
    STATE(18), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_conditional_expression,
      sym_literal,
  [294] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_null_literal,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(25), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_reference,
      sym_member_access,
    STATE(17), 2,
      sym_boolean_literal,
      sym_string,
    STATE(18), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_conditional_expression,
      sym_literal,
  [335] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_null_literal,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(29), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_reference,
      sym_member_access,
    STATE(17), 2,
      sym_boolean_literal,
      sym_string,
    STATE(18), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_conditional_expression,
      sym_literal,
  [376] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_null_literal,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(27), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_reference,
      sym_member_access,
    STATE(17), 2,
      sym_boolean_literal,
      sym_string,
    STATE(18), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_conditional_expression,
      sym_literal,
  [417] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_null_literal,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(33), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_reference,
      sym_member_access,
    STATE(17), 2,
      sym_boolean_literal,
      sym_string,
    STATE(18), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_conditional_expression,
      sym_literal,
  [458] = 2,
    ACTIONS(29), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(31), 16,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
      anon_sym_DOT,
  [481] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_null_literal,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(30), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_reference,
      sym_member_access,
    STATE(17), 2,
      sym_boolean_literal,
      sym_string,
    STATE(18), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_conditional_expression,
      sym_literal,
  [522] = 11,
    ACTIONS(5), 1,
      anon_sym_LPAREN,
    ACTIONS(9), 1,
      sym_number_literal,
    ACTIONS(13), 1,
      sym_null_literal,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      sym_identifier,
    STATE(34), 1,
      sym_expression,
    ACTIONS(7), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(11), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_reference,
      sym_member_access,
    STATE(17), 2,
      sym_boolean_literal,
      sym_string,
    STATE(18), 4,
      sym_unary_expression,
      sym_binary_expression,
      sym_conditional_expression,
      sym_literal,
  [563] = 2,
    ACTIONS(33), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(35), 15,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [585] = 2,
    ACTIONS(19), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 15,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [607] = 2,
    ACTIONS(37), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(39), 15,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [629] = 2,
    ACTIONS(41), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(43), 15,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [651] = 2,
    ACTIONS(45), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(47), 15,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [673] = 4,
    ACTIONS(49), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(55), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(51), 10,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [699] = 2,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 15,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [721] = 2,
    ACTIONS(49), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 15,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [743] = 5,
    ACTIONS(53), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(51), 8,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [771] = 2,
    ACTIONS(65), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 15,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [793] = 7,
    ACTIONS(71), 1,
      anon_sym_AMP_AMP,
    ACTIONS(53), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(69), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(55), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(51), 5,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [825] = 3,
    ACTIONS(49), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(51), 12,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_PLUS,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [849] = 6,
    ACTIONS(53), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(69), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(55), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(51), 6,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_QMARK,
      anon_sym_COLON,
  [879] = 9,
    ACTIONS(71), 1,
      anon_sym_AMP_AMP,
    ACTIONS(75), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(77), 1,
      anon_sym_QMARK,
    ACTIONS(53), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(69), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(55), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(73), 3,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COLON,
  [915] = 9,
    ACTIONS(71), 1,
      anon_sym_AMP_AMP,
    ACTIONS(75), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(77), 1,
      anon_sym_QMARK,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
    ACTIONS(53), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(69), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(55), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [949] = 9,
    ACTIONS(71), 1,
      anon_sym_AMP_AMP,
    ACTIONS(75), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(77), 1,
      anon_sym_QMARK,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(69), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(55), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [983] = 9,
    ACTIONS(71), 1,
      anon_sym_AMP_AMP,
    ACTIONS(75), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(77), 1,
      anon_sym_QMARK,
    ACTIONS(83), 1,
      anon_sym_COLON,
    ACTIONS(53), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(69), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(55), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [1017] = 9,
    ACTIONS(71), 1,
      anon_sym_AMP_AMP,
    ACTIONS(75), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(77), 1,
      anon_sym_QMARK,
    ACTIONS(85), 1,
      anon_sym_RBRACE,
    ACTIONS(53), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(69), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(55), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [1051] = 5,
    ACTIONS(87), 1,
      anon_sym_LT_SLASH,
    ACTIONS(89), 1,
      anon_sym_LBRACE,
    ACTIONS(91), 1,
      sym_text,
    STATE(49), 1,
      sym_expression_block,
    STATE(39), 2,
      sym_child,
      aux_sym_container_element_repeat1,
  [1068] = 5,
    ACTIONS(89), 1,
      anon_sym_LBRACE,
    ACTIONS(91), 1,
      sym_text,
    ACTIONS(93), 1,
      anon_sym_LT_SLASH,
    STATE(49), 1,
      sym_expression_block,
    STATE(39), 2,
      sym_child,
      aux_sym_container_element_repeat1,
  [1085] = 5,
    ACTIONS(89), 1,
      anon_sym_LBRACE,
    ACTIONS(91), 1,
      sym_text,
    ACTIONS(93), 1,
      anon_sym_LT_SLASH,
    STATE(49), 1,
      sym_expression_block,
    STATE(35), 2,
      sym_child,
      aux_sym_container_element_repeat1,
  [1102] = 5,
    ACTIONS(89), 1,
      anon_sym_LBRACE,
    ACTIONS(91), 1,
      sym_text,
    ACTIONS(95), 1,
      anon_sym_LT_SLASH,
    STATE(49), 1,
      sym_expression_block,
    STATE(36), 2,
      sym_child,
      aux_sym_container_element_repeat1,
  [1119] = 5,
    ACTIONS(97), 1,
      anon_sym_LT_SLASH,
    ACTIONS(99), 1,
      anon_sym_LBRACE,
    ACTIONS(102), 1,
      sym_text,
    STATE(49), 1,
      sym_expression_block,
    STATE(39), 2,
      sym_child,
      aux_sym_container_element_repeat1,
  [1136] = 3,
    ACTIONS(107), 1,
      sym_identifier,
    ACTIONS(105), 2,
      anon_sym_SLASH_GT,
      anon_sym_GT,
    STATE(40), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [1148] = 4,
    ACTIONS(110), 1,
      anon_sym_SLASH_GT,
    ACTIONS(112), 1,
      anon_sym_GT,
    ACTIONS(114), 1,
      sym_identifier,
    STATE(42), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [1162] = 4,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(116), 1,
      anon_sym_SLASH_GT,
    ACTIONS(118), 1,
      anon_sym_GT,
    STATE(40), 2,
      sym_attribute,
      aux_sym_self_closing_element_repeat1,
  [1176] = 3,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
    ACTIONS(122), 1,
      anon_sym_DQUOTE,
    STATE(46), 2,
      sym_expression_block,
      sym_string,
  [1187] = 1,
    ACTIONS(47), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_identifier,
  [1193] = 2,
    ACTIONS(126), 1,
      sym_text,
    ACTIONS(124), 2,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [1201] = 1,
    ACTIONS(128), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_identifier,
  [1207] = 1,
    ACTIONS(67), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_identifier,
  [1213] = 1,
    ACTIONS(126), 3,
      anon_sym_SLASH_GT,
      anon_sym_GT,
      sym_identifier,
  [1219] = 2,
    ACTIONS(132), 1,
      sym_text,
    ACTIONS(130), 2,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE,
  [1227] = 2,
    ACTIONS(134), 1,
      anon_sym_DQUOTE,
    ACTIONS(136), 1,
      sym_string_content,
  [1234] = 2,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    ACTIONS(140), 1,
      sym_string_content,
  [1241] = 1,
    ACTIONS(142), 1,
      anon_sym_GT,
  [1245] = 1,
    ACTIONS(144), 1,
      sym_tag_name,
  [1249] = 1,
    ACTIONS(146), 1,
      ts_builtin_sym_end,
  [1253] = 1,
    ACTIONS(148), 1,
      anon_sym_DQUOTE,
  [1257] = 1,
    ACTIONS(150), 1,
      sym_identifier,
  [1261] = 1,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
  [1265] = 1,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
  [1269] = 1,
    ACTIONS(156), 1,
      anon_sym_EQ,
  [1273] = 1,
    ACTIONS(158), 1,
      anon_sym_GT,
  [1277] = 1,
    ACTIONS(160), 1,
      sym_tag_name,
  [1281] = 1,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
  [1285] = 1,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
  [1289] = 1,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
  [1293] = 1,
    ACTIONS(168), 1,
      ts_builtin_sym_end,
  [1297] = 1,
    ACTIONS(170), 1,
      sym_tag_name,
  [1301] = 1,
    ACTIONS(172), 1,
      anon_sym_GT,
  [1305] = 1,
    ACTIONS(174), 1,
      sym_tag_name,
  [1309] = 1,
    ACTIONS(176), 1,
      ts_builtin_sym_end,
  [1313] = 1,
    ACTIONS(178), 1,
      anon_sym_DQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 107,
  [SMALL_STATE(6)] = 130,
  [SMALL_STATE(7)] = 171,
  [SMALL_STATE(8)] = 212,
  [SMALL_STATE(9)] = 253,
  [SMALL_STATE(10)] = 294,
  [SMALL_STATE(11)] = 335,
  [SMALL_STATE(12)] = 376,
  [SMALL_STATE(13)] = 417,
  [SMALL_STATE(14)] = 458,
  [SMALL_STATE(15)] = 481,
  [SMALL_STATE(16)] = 522,
  [SMALL_STATE(17)] = 563,
  [SMALL_STATE(18)] = 585,
  [SMALL_STATE(19)] = 607,
  [SMALL_STATE(20)] = 629,
  [SMALL_STATE(21)] = 651,
  [SMALL_STATE(22)] = 673,
  [SMALL_STATE(23)] = 699,
  [SMALL_STATE(24)] = 721,
  [SMALL_STATE(25)] = 743,
  [SMALL_STATE(26)] = 771,
  [SMALL_STATE(27)] = 793,
  [SMALL_STATE(28)] = 825,
  [SMALL_STATE(29)] = 849,
  [SMALL_STATE(30)] = 879,
  [SMALL_STATE(31)] = 915,
  [SMALL_STATE(32)] = 949,
  [SMALL_STATE(33)] = 983,
  [SMALL_STATE(34)] = 1017,
  [SMALL_STATE(35)] = 1051,
  [SMALL_STATE(36)] = 1068,
  [SMALL_STATE(37)] = 1085,
  [SMALL_STATE(38)] = 1102,
  [SMALL_STATE(39)] = 1119,
  [SMALL_STATE(40)] = 1136,
  [SMALL_STATE(41)] = 1148,
  [SMALL_STATE(42)] = 1162,
  [SMALL_STATE(43)] = 1176,
  [SMALL_STATE(44)] = 1187,
  [SMALL_STATE(45)] = 1193,
  [SMALL_STATE(46)] = 1201,
  [SMALL_STATE(47)] = 1207,
  [SMALL_STATE(48)] = 1213,
  [SMALL_STATE(49)] = 1219,
  [SMALL_STATE(50)] = 1227,
  [SMALL_STATE(51)] = 1234,
  [SMALL_STATE(52)] = 1241,
  [SMALL_STATE(53)] = 1245,
  [SMALL_STATE(54)] = 1249,
  [SMALL_STATE(55)] = 1253,
  [SMALL_STATE(56)] = 1257,
  [SMALL_STATE(57)] = 1261,
  [SMALL_STATE(58)] = 1265,
  [SMALL_STATE(59)] = 1269,
  [SMALL_STATE(60)] = 1273,
  [SMALL_STATE(61)] = 1277,
  [SMALL_STATE(62)] = 1281,
  [SMALL_STATE(63)] = 1285,
  [SMALL_STATE(64)] = 1289,
  [SMALL_STATE(65)] = 1293,
  [SMALL_STATE(66)] = 1297,
  [SMALL_STATE(67)] = 1301,
  [SMALL_STATE(68)] = 1305,
  [SMALL_STATE(69)] = 1309,
  [SMALL_STATE(70)] = 1313,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_member_access, 3, 0, 7),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_member_access, 3, 0, 7),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 3),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 3),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 6),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 6),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 5),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 5),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_expression, 5, 0, 8),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_container_element_repeat1, 2, 0, 0),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_container_element_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_container_element_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_self_closing_element_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_self_closing_element_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_block, 3, 0, 4),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_block, 3, 0, 4),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 2),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_child, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 3, 0, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 4, 0, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [162] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_container_element, 8, 0, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_container_element, 7, 0, 1),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_container_element, 6, 0, 1),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mprx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mprx",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
